# (C) Copyright IBM Corporation 2021.
# LICENSE: GPL-3.0 https://opensource.org/licenses/GPL-3.0
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: networkservices.gnforchestrator.ibm.com
spec:
  group: gnforchestrator.ibm.com
  names:
    kind: NetworkService
    listKind: NetworkServiceList
    plural: networkservices
    singular: networkservice
    shortNames:
    - nsvc
  scope: Namespaced
  subresources:
    status: {}
    scale:
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.replicas
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          type: object
          properties:
            properties:
              type: object
            components:
              type: object
            statusTemplate:
              type: object
            replicas:
              type: integer
        status:
          type: object
          properties:
            ip:
              type: string
            port:
              type: integer
  additionalPrinterColumns:
  - name: ip
    JSONPath: .status.ip
    type: string
  - name: port
    JSONPath: .status.port
    type: integer
  versions:
  - name: v2alpha1
    served: true
    storage: true
